version: "3.8"

services:
  pd_container:
    image: postgres
    container_name: todo_db_container
    environment:
       - POSTGRES_PASSWORD=1234
      #  - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
    - 5432:5432
    volumes:
    - databases_volume:/var/lib/mysql
volumes:
  databases_volume:

# version: "3.8"

# services:
#   db:
#     image: mariadb
#     restart: always
#     environment:
#       - MARIADB_ROOT_PASSWORD=1234
#     volumes:
#       - ./databases:/var/lib/mysql
#     ports:
#       - 3306:3306